spring:
  application:
    name: spring-boot-monog
logging:
  file: app.log

server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
spring.data.mongodb.uri: mongodb://moviedb:27017/spring-mongo
